import type { Metadata } from "next";
import Animator from "@/components/Animator";
import React from "react";

export const metadata: Metadata = {
    title: "Creati | Authenticate",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
            <Animator>
                {children}
            </Animator>
    );
}
