import type { Metadata } from "next";
import { Space_Grotesk, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import ApiKeyProvider from "@/context/ApiKeyContext";
import ProviderLayout from "@/components/ProviderLayout";
import {getServerSession} from "next-auth";
import {authOptions} from "@/lib/auth";

const spaceGrotesk = Space_Grotesk({
    variable: "--font-space-grotesk",
    subsets: ["latin"]
});

const ibmPlexMono = IBM_Plex_Mono({
    variable: "--font-ibm-plex-mono",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
    title: "Creati | Create flowcharts in an instant",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {

    const session = await getServerSession(authOptions)

    return (
        <html lang="en">
        <body
            className={`${spaceGrotesk.variable} ${ibmPlexMono.variable} antialiased selection:bg-blue-500/10`}
        >
        <ApiKeyProvider>
            <ProviderLayout session={session}>
                {children}
            </ProviderLayout>
        </ApiKeyProvider>
        </body>
        </html>
    );
}
